version: 2
updates:
  - package-ecosystem: npm
    directory: /web-app
    schedule:
      interval: monthly
    groups:
      patch-and-minor:
        update-types: [minor, patch]
        exclude-patterns:
          - nitro
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
