/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHabitsRouteImport } from './routes/api/habits'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as HealthLiveRouteImport } from './routes/health/live'
import { Route as HealthReadyRouteImport } from './routes/health/ready'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiHabitsHabitIdRouteImport } from './routes/api/habits/$habitId'
import { Route as ApiHabitsHabitIdArchiveRouteImport } from './routes/api/habits/$habitId/archive'
import { Route as ApiHabitsHabitIdCompleteRouteImport } from './routes/api/habits/$habitId/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsRoute = ApiHabitsRouteImport.update({
  id: '/api/habits',
  path: '/api/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/health/live',
  path: '/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/health/ready',
  path: '/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHabitsHabitIdRoute = ApiHabitsHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => ApiHabitsRoute,
} as any)
const ApiHabitsHabitIdArchiveRoute = ApiHabitsHabitIdArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ApiHabitsHabitIdRoute,
} as any)
const ApiHabitsHabitIdCompleteRoute =
  ApiHabitsHabitIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiHabitsHabitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/home': typeof ApiHomeRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/habits/$habitId': typeof ApiHabitsHabitIdRouteWithChildren
  '/api/habits/$habitId/archive': typeof ApiHabitsHabitIdArchiveRoute
  '/api/habits/$habitId/complete': typeof ApiHabitsHabitIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/home': typeof ApiHomeRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/habits/$habitId': typeof ApiHabitsHabitIdRouteWithChildren
  '/api/habits/$habitId/archive': typeof ApiHabitsHabitIdArchiveRoute
  '/api/habits/$habitId/complete': typeof ApiHabitsHabitIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/habits': typeof ApiHabitsRouteWithChildren
  '/api/home': typeof ApiHomeRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/habits/$habitId': typeof ApiHabitsHabitIdRouteWithChildren
  '/api/habits/$habitId/archive': typeof ApiHabitsHabitIdArchiveRoute
  '/api/habits/$habitId/complete': typeof ApiHabitsHabitIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/habits'
    | '/api/home'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/habits/$habitId'
    | '/api/habits/$habitId/archive'
    | '/api/habits/$habitId/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/habits'
    | '/api/home'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/habits/$habitId'
    | '/api/habits/$habitId/archive'
    | '/api/habits/$habitId/complete'
  id:
    | '__root__'
    | '/'
    | '/api/habits'
    | '/api/home'
    | '/health/live'
    | '/health/ready'
    | '/api/auth/$'
    | '/api/habits/$habitId'
    | '/api/habits/$habitId/archive'
    | '/api/habits/$habitId/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHabitsRoute: typeof ApiHabitsRouteWithChildren
  ApiHomeRoute: typeof ApiHomeRoute
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits': {
      id: '/api/habits'
      path: '/api/habits'
      fullPath: '/api/habits'
      preLoaderRoute: typeof ApiHabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/live': {
      id: '/health/live'
      path: '/health/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/health/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/habits/$habitId': {
      id: '/api/habits/$habitId'
      path: '/$habitId'
      fullPath: '/api/habits/$habitId'
      preLoaderRoute: typeof ApiHabitsHabitIdRouteImport
      parentRoute: typeof ApiHabitsRoute
    }
    '/api/habits/$habitId/archive': {
      id: '/api/habits/$habitId/archive'
      path: '/archive'
      fullPath: '/api/habits/$habitId/archive'
      preLoaderRoute: typeof ApiHabitsHabitIdArchiveRouteImport
      parentRoute: typeof ApiHabitsHabitIdRoute
    }
    '/api/habits/$habitId/complete': {
      id: '/api/habits/$habitId/complete'
      path: '/complete'
      fullPath: '/api/habits/$habitId/complete'
      preLoaderRoute: typeof ApiHabitsHabitIdCompleteRouteImport
      parentRoute: typeof ApiHabitsHabitIdRoute
    }
  }
}

interface ApiHabitsHabitIdRouteChildren {
  ApiHabitsHabitIdArchiveRoute: typeof ApiHabitsHabitIdArchiveRoute
  ApiHabitsHabitIdCompleteRoute: typeof ApiHabitsHabitIdCompleteRoute
}

const ApiHabitsHabitIdRouteChildren: ApiHabitsHabitIdRouteChildren = {
  ApiHabitsHabitIdArchiveRoute: ApiHabitsHabitIdArchiveRoute,
  ApiHabitsHabitIdCompleteRoute: ApiHabitsHabitIdCompleteRoute,
}

const ApiHabitsHabitIdRouteWithChildren =
  ApiHabitsHabitIdRoute._addFileChildren(ApiHabitsHabitIdRouteChildren)

interface ApiHabitsRouteChildren {
  ApiHabitsHabitIdRoute: typeof ApiHabitsHabitIdRouteWithChildren
}

const ApiHabitsRouteChildren: ApiHabitsRouteChildren = {
  ApiHabitsHabitIdRoute: ApiHabitsHabitIdRouteWithChildren,
}

const ApiHabitsRouteWithChildren = ApiHabitsRoute._addFileChildren(
  ApiHabitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHabitsRoute: ApiHabitsRouteWithChildren,
  ApiHomeRoute: ApiHomeRoute,
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
